package com.example.demo.endpoints;

import com.example.demo.entity.ObjectsData;
import com.example.demo.services.ObjectService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.List;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class ObjectController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ObjectService service;

//    @PostMapping(path="/add") // Map ONLY POST Requests
//    public @ResponseBody String addNewUser (@RequestParam String name
//            , @RequestParam String email) {
//        // @ResponseBody means the returned String is the response, not a view name
//        // @RequestParam means it is a parameter from the GET or POST request
//
//        User n = new User();
//        n.setName(name);
//        n.setEmail(email);
//        userRepository.save(n);
//        return "Saved";
//    }
    @RequestMapping("/")
    private String viewHomePage (Model model){
        List<ObjectsData> tourismObjectList = service.getList();
        model.addAttribute("tourismObject", tourismObjectList);
       return "index";
    }

    @GetMapping(path="/all")
    public @ResponseBody
    List<ObjectsData> getAllObjects() {
        // This returns a JSON or XML with the users
        return service.getList();
    }

    @GetMapping(path="{id}")
    public @ResponseBody
    ObjectsData getObject(@PathVariable int id) {
        // This returns a JSON or XML with the users
        return service.get(id);
    }
}
